name: Release Pipeline
run-name: ${{ github.actor }} is running the release pipeline
on:
  workflow_dispatch:

jobs:
  testing:
    uses: ./.github/workflows/rust.yml

  publish:
    needs: testing
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo login
      - run: cargo publish
    env: # Or as an environment variable
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
