name: Test Pipeline
run-name: ${{ github.actor }} is running the test pipeline
on: [push]
jobs:
  cargo-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
      - run: cargo test

  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  cargo-clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy -- -D warnings
